name: BlockRestore
main: io.github.kazarp.blockrestore.BlockRestore
version: 2.0
commands:
   blocksave:
      description: Saves selected blocks with a name
      usage: /<command> [name] or /<command> [name] [x1] [y1] [z1] [x2] [y2] [z2]
      permission: <plugin name>.save
      permission-message: You don't have <permission>
   blockrestore:
      description: Restores an area with a name
      usage: /<command> [name]
      permission: <plugin name>.restore
      permission-message: You don't have <permission>
   blockremove:
      description: Removes the save of an area
      usage: /<command> [name]
      permission: <plugin name>.remove
      permission-message: You don't have <permission>
   blocklist:
      description: Lists saved areas
      usage: /<command>
      permission: <plugin name>.list
      permission-message: You don't have <permission>
permissions:
    blockrestore.*:
        description: Gives access to all BlockRestore commands
        children:
            blockrestore.save: true
            blockrestore.restore: true
            blockrestore.remove: true
            blockrestore.list: true
    blockrestore.save:
        description: Allows you to save an area
        default: op
    blockrestore.restore:
        description: Allows you to restore an area
        default: op
    blockrestore.remove:
        description: Allows you to remove an area
        default: op
    blockrestore.list:
        description: Allows you to list available saved areas
        default: op